sudo: required
dist: trusty
language: objective-c

install: Scripts/install.sh
script: Scripts/build.sh

os:
  - osx
  - linux

notifications:
  - slack: dwarfoftherap:6MsfPkyRctI0nrGYkLsN9J7k
  - email: false
